# 服务端口
server:
  port: 8010

# Eureak注册中心
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    ### Eureka Server的高可用就是将自己作为服务向其他服务注册中心注册自己，以形成一组互相注册的服务注册中心，以实现服务清单的互相同步，达到高可用的效果
    # 当前服务就是注册中心，不向注册中心注册(false)
    registerWithEureka: true
    # 注册中心的职责就是维护服务实例，它并不需要去检索服务
    fetchRegistry: false
    serviceUrl:
      # Eureka Server高可用集群时，defaultZone为其他注册中心url，而Eureka Client时，有多少个注册中心，就要配置多少个，以实现高可用
      # 多个url间用逗号“,”，隔开
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

# spring配置
spring:
  # 服务名配置
  application:
    name: scmp-registry-ampq
  zipkin:
    sleuth:
      sampler:
        percentage: 1.0
    sender:
      type: rabbit
    rabbitmq:
      queue: zipkin-demo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  ##### config配置存储在config-server服务的shared文件下 #####
  #  profiles:
  #    active: native
  ##### config配置存储在config-server服务的shared文件下 #####
  cloud:
    config:
      server:
        ##### config配置存储在config-server服务的shared文件下 #####
        #        native:
        #          search-locations: classpath:/shared
        ##### config配置存储在config-server服务的shared文件下 #####
        ##### config配置存储在Git #####
        git:
          #服务的git仓库地址
          uri: https://gitee.com/xuesjie/scmp-common-service.git
          search-paths: src/main/resources/shared
          #用户名和密码
          username: sjxue126@126.com
          password: xsj890702<>
        default-label: develop
        ##### config配置存储在Git #####
    bus:
      trace:
        enabled: true
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    web:
      server:
        auto-time-requests: false

logging:
  config: classpath:logback-spring.xml