server:
  port: 8015

spring:
  application:
    name: kunlun-gateway-service

shiro:
  secret: 61D73234C4F93E03074D74D74D1E39D9
  expireTime: 1800000
  tokenHeader: Authorization
  ignoreUrls: /kunlun-gateway-service/shiro/login, /kunlun-basedata-service/code/getAuthCode, /kunlun-gateway-service/shiro/logout

zuul:
  # 饥饿加载，防止懒加载时第一次请求超时而失败
  eager-load:
    enabled: true
  #是否开启路由重试
  retryable: true
  host:
    socket-timeout-millis: 300000
    connect-timeout-millis: 300000
  routes:
    registry-amqp:
      path: /kunlun-register-service/**
      serviceId: kunlun-register-service
    gate-way:
      path: /kunlun-gateway-service/**
      serviceId: kunlun-gateway-service
    base-cache:
      path: /kunlun-basedata-service/**
      serviceId: kunlun-basedata-service
    system-service:
      path: /kunlun-system-service/**
      serviceId: kunlun-system-service
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin

ribbon:
  # 饥饿加载，防止懒加载时第一次请求超时而失败
  eager-load:
    enabled: true
    clients: kunlun-basedata-service, kunlun-system-service
  eureka:
    enabled: true
  ReadTimeout: 300000
  ConnectTimeout: 300000
  SocketTimeout: 300000
  #对当前实例的重试次数
  MaxAutoRetries: 1
  #切换实例的重试次数
  MaxAutoRetriesNextServer: 1
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: true