server:
  port: 8015

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
    # 抓取服务列表时间间隔
    registry-fetch-interval-seconds: 30
  instance:
    # 启用ip配置 这样在注册中心列表中看见的是以ip+端口呈现的
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 30

spring:
  application:
    name: scmp-gate-way
  cloud:
    loadbalancer:
      #该参数用来开启重试机制，默认是关闭
      retry:
        enabled: true
  zipkin:
    sleuth:
      sampler:
        percentage: 1.0
    sender:
      type: rabbit
    rabbitmq:
      queue: zipkin-demo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    #confirm模式
    publisher-confirms: true
    #return机制
    publisher-returns: true

shiro:
  secret: 61D73234C4F93E03074D74D74D1E39D9
  expireTime: 1800000
  tokenHeader: Authorization
  ignoreUrls: /gate-way/shiro/login, /basedata-cache/code/getAuthCode, /gate-way/shiro/logout

zuul:
  # 饥饿加载，防止懒加载时第一次请求超时而失败
  eager-load:
    enabled: true
  #是否开启路由重试
  retryable: true
  host:
    socket-timeout-millis: 300000
    connect-timeout-millis: 300000
  routes:
    registry-amqp:
      path: /registry-amqp/**
      serviceId: scmp-registry-ampq
    gate-way:
      path: /gate-way/**
      serviceId: scmp-gate-way
    base-cache:
      path: /basedata-cache/**
      serviceId: scmp-basedata-cache
    system-service:
      path: /system-service/**
      serviceId: scmp-system-service
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

ribbon:
  # 饥饿加载，防止懒加载时第一次请求超时而失败
  eager-load:
    enabled: true
    clients: scmp-basedata-cache, scmp-system-service
  eureka:
    enabled: true
  ReadTimeout: 300000
  ConnectTimeout: 300000
  SocketTimeout: 300000
  #对当前实例的重试次数
  MaxAutoRetries: 1
  #切换实例的重试次数
  MaxAutoRetriesNextServer: 1
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: true

feign.hystrix.enabled: true

hystrix:
  shareSecurityContext: true
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 360000
        forceClosed: true
      execution:
        isolation:
          thread:
            # hystrix 超时时间最好大于Ribbon的超时时间
            timeoutInMilliseconds: 360000
        timeout:
          enabled: true

logging:
  config: classpath:logback-spring.xml