server:
  port: 8015

spring:
  application:
    name: kunlun-gateway-service

shiro:
  secret: 61D73234C4F93E03074D74D74D1E39D9
  expireTime: 1800000
  tokenHeader: Authorization
  ignoreUrls: /kunlun-gateway-service/shiro/login, /kunlun-basedata-service/code/getAuthCode, /kunlun-gateway-service/shiro/logout

zuul:
  # 饥饿加载，防止懒加载时第一次请求超时而失败
  eager-load:
    enabled: true
  #是否开启路由重试
  retryable: true
  host:
    max-total-connections: 200
    max-per-route-connections: 20
    socket-timeout-millis: 10000
    connect-timeout-millis: 10000
  routes:
    register:
      path: /kunlun-register-service/**
      serviceId: kunlun-register-service
    gateway:
      path: /kunlun-gateway-service/**
      serviceId: kunlun-gateway-service
    basedata:
      path: /kunlun-basedata-service/**
      serviceId: kunlun-basedata-service
    system:
      path: /kunlun-system-service/**
      serviceId: kunlun-system-service
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin

turbine:
  # 配置 Eureka 中的 serviceId 列表，指定要监控的服务
  app-config: kunlun-gateway-service, kunlun-basedata-service, kunlun-system-service
  aggregator:
    cluster-config: default
  # 指定集群名称
  cluster-name-expression: "'default'"

ribbon:
  # 饥饿加载，防止懒加载时第一次请求超时而失败
  eager-load:
    enabled: true
    clients: kunlun-basedata-service, kunlun-system-service
  eureka:
    enabled: true
  ReadTimeout: 10000
  ConnectTimeout: 10000
  SocketTimeout: 10000
  #对当前实例的重试次数
  MaxAutoRetries: 1
  #切换实例的重试次数
#  MaxAutoRetriesNextServer: 1
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: true

# 系统自动配置项
kunlun:
  # swagger配置
  swagger:
    enable: true
    basePackage: com.kunlun.gateway.controller
    title: ${spring.application.name}服务Swagger文档
    description: 系统业务接口服务
    version: 1.0.0
