# 服务端口
server:
  port: 8020

# Eureak注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

# spring配置
spring:
  # 服务名配置
  application:
    name: scmp-base-cache
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scmp_home
    username: postgres
    password: java
    continue-on-error: true
  zipkin:
    sleuth:
      sampler:
        percentage: 1.0
    sender:
      type: rabbit
    rabbitmq:
      queue: zipkin-demo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 127.0.0.1
    port: 6379
    # Redis数据库索引（默认为0）
    database: 0
    # 连接超时时间（毫秒）
    timeout: 3000
    # config for redis
    jedis:
      pool:
        # 最小空闲连接数
        min-idle: 50
        # 最大空闲连接数
        max-idle: 500
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1
        # 最大活跃连接数，负数为不限制
        max-active: 50
  flyway:
    # 是否开启flywary，默认true
    enabled: true
    # 设置迁移时的编码，默认UTF-8
    encoding: UTF-8
    # 迁移脚本的位置，默认db/db.migration
    locations: classpath:migration
    # 迁移文件的前缀，默认为V
    sql-migration-prefix: V
    # 迁移脚本的文件名分隔符，默认__
    sql-migration-separator: __
    # 迁移脚本的后缀，默认为.sql
    sql-migration-suffixes: .sql
    # 迁移时是否校验，默认为true
    validate-on-migrate: true
    # 设定需要flywary迁移的schema，大小写敏感，默认为连接默认的schema
    schemas: public
    # flyway使用的元数据表名，默认为schema_version
    table: schema_versions
    # 当迁移时发现目标schema非空，而且带有没有元数据的表时，是否自动执行基准迁移，默认false
    baseline-on-migrate: true
    # 是否允许无序的迁移，默认false
    out-of-order: true
    # 开始执行基准迁移时对现有的schema的版本打标签，默认值为1
    baseline-version: 1.0.0
    # 对执行迁移时基准版本的描述
    baseline-description: "initial flyway"

zipkin:
  # zipkin采样频率设置
  sleuth:
    enabled: false
    sampler:
      percentage: 1.0
  storage:
    type: elasticsearch
    StorageComponent: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      max-requests: 30
      index: zipkin-es
      index-shards: 3
      index-replicas: 1
      hosts: localhost:9200
  sender:
    type: rabbit
  collector:
    #rabbitmq配置
    rabbitmq:
      addresses: localhost:5672
      username: guest
      password: guest
      queue: zipkin-demo

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.scmp.base.model
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    web:
      server:
        auto-time-requests: false

logging:
  config: classpath:logback-spring.xml